/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b31ee2d7-c2e5-4872-b28b-f547d3ccbfd1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_2IJrHIgKk",
    "aws_user_pools_web_client_id": "i03k4jdk88p8qbhpnl4onbv5t",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://hermgmglcjcjjj4d5qs5ba3bqe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ptl64zmzpzamjeat5mn6ci5nju"
};


export default awsmobile;
